### ISSUE TITLE
The API url changed, again

### ISSUE THREAD

**Issue by haarts** [42minutes/go-trakt#5]
It's now `https://api-v2launch.trakt.tv`. The const `TraktAPIURL` should be changed to reflect this.

Workaround is using `trakt.NewClientWith(....)`.

**Comment by 2buisson** [comment]
And it seems the whole Go program crash because of it, I think it should throw an error instead.
Nice library btw, thanks.

**Comment by geoah** [comment]
Need to get around fixing various parts of this sorry. Gimme till tomorrow! :)

**Comment by geoah** [comment]
BTW @superdecimal fixed this one with https://github.com/42minutes/go-trakt/commit/c1705d4457cf2151efb39f6b5f6366e8abc815b2 quite some time ago, just forgot to close this issue :)
