### ISSUE TITLE
ID Lookup: search a show by id

### ISSUE THREAD

**Issue by 2buisson** [42minutes/go-trakt#6]
http://docs.trakt.apiary.io/#reference/search/id-lookup/get-id-lookup-results

I tried to add the feature myself, as you can see here: https://github.com/varyoo/go-trakt/blob/id-lookup/shows.go#L42, unfortunately it dosen't works well.

Take the following code:

``` go
_, res := trakt.Shows().IdLookup("tvdb", 269613)
println(res.Err.Error())
```

Output: `json: cannot unmarshal string into Go value of type int`

I'm not sure why, but I guess it's because we can't specify the type of the results for an ID Lookup (I  tried to append `&type=show` to the URL it dosen't work), so the json parser run into other types of results. (an episode in this case).

Thanks for any help.

**Comment by geoah** [comment]
Hey @varyoo I added a `OneOfType` for shows, try this, I made the id a string as imdb ids start with stuff like tt.

```
showByID, err := client.Shows().OneOfType("tt2802850", "imdb")
fmt.Println(showByID)
```

I really need to take some time to refactor this library, it was one of my first things with golang and it really could use proper error handling etc.

**Comment by 2buisson** [comment]
Wow I wasn't expecting a solution so fast! Thanks @geoah 

This is what I needed, I see we should check on `showByID` being `nil` for errors.
Also, since `&type=show` dosen't work, are we sure the show will always be the first result in Trakt?

A good one for a first dive into Golang, looking forward to this refactoring!
